### ISSUE TITLE
[kube-prometheus-stack] kube-state-metrics 데이터를 수집 못하는 버그

### ISSUE THREAD

**Issue by choshsh** [choshsh/devops-study#131]
## 이슈

helm 차트로 kube-prometheus-stack 설치 시, prometheus가 kube-state-metrics의 데이터를 수집하지 않는다.

## 환경

| 이름 | 버전 |
| --- | --- |
| kube-prometheus-stack 차트 | 27.2.1 |
| kubernetes cluster / kubectl | 1.23.1 |
| helm | 3.7.2 |

## 조사

kube-prometheus-stack 차트는 [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator)를 통해서  배포, 설정 등을 관리한다.

prometheus와 kube-state-metrics의 설정을 관리하는 CRD를 살펴봤다.

1. prometheus (CRD)
    
    ```yaml
    $ k get -n monitor prometheus p-kube-prometheus-stack-prometheus -oyaml
    
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    ...
      serviceMonitorSelector:
        matchLabels:
          release: p
    ```
    
    `release: p`  레이블을 가진 serviceMonitor의 데이터를 수집하도록 되어있다.
    
2. kube-state-metrics의 serviceMonitor (CRD)
    
    ```yaml
    $ k get -n monitor servicemonitors.monitoring.coreos.com p-kube-state-metrics -oyaml
    
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: p
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/part-of: kube-state-metrics
        app.kubernetes.io/version: 2.3.0
        helm.sh/chart: kube-state-metrics-4.2.
    
    ```
    
    하... `release: p` 레이블이 없다... 
    
    다른 serviceMonitor들은 레이블이 멀쩡하게 잘 있는데 왜 얘만 이런지 모르겠다.
    

## 원인

차트 설치 시 kube-state-metrics의 serviceMonitor에 `release: <helm 배포 이름>` 레이블이 누락되어 prometheus가 데이터를 수집하지 않았다.

## 해결방법

kube-state-metric의 serviceMonitor에 레이블을 추가한다.

```yaml
# values-custom.yaml
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        release: p # helm 배포 이름
```

단순 버그인거 같으니 조만간 수정될 것 같다.
정리하고 나서 보니 간단해보이는데 며칠을 고생했다😂 그래도 prometheus-operator의 컨셉을 조금 이해하고 설정 관련 커스텀 리소스들을 더 들여다본 좋은 경험이었다.
